# generated : 2019-12-29:15:53  // template : ./setup/template/docker-compose.jinja2

version: "3.5"

networks:
  taginfo:
    name: taginfo

services:

  #---------------------------------------------------------
  # Service for : "ru"-"Russia" + taginfo-dev.opengeodata.hu
  #               continent: "ru"

  taginfo-ru-ru:
    user: ${CURRENT_UID}
    restart: always
    image: taginfo_view
    ports:
      - "24001:4567"
    networks:
      - taginfo
    environment:
      - VIRTUAL_HOST=ru-ru.taginfo-dev.opengeodata.hu
      - VIRTUAL_PORT=4567
      - MAPPED_PORT=24001
    volumes:
     - ./ru/data:/osm/data
     - ./ru/download:/osm/download
     - ./ru:/osm/cfg
     - ../../sh:/osm/sh:ro


# generated : 2019-12-29:15:53  // template : /setup/docker-compose.jinja2